# https://towardsdatascience.com/the-complete-guide-to-docker-volumes-1a06051d2cce
version: '3.4'

services:
  basketdb:
    container_name: IngredientDb
    restart: always
    ports:
      - "6379:6379"

  IngredientDb:
    container_name: basketdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  ingredient.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://IngredientDb:27017"
    depends_on:
      - IngredientDb
    ports:
      - "8000:80"
   
  mongo_express:
     environment:
      - ME_CONFIG_MONGODB_SERVER=IngredientDb
     ports:
      - "8081:8081"
     depends_on:
      - IngredientDb

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"


  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

